### ISSUE TITLE
Appsody docker pull issue on Macbook M1

### ISSUE THREAD

**Issue by dawoodahmed-jazz** [appsody/appsody-docker#21]
I am getting the following error while pulling the Appsody image on my MacBook M1 chipset.

```
unning development environment...
Using local cache for image dev.local/appsody/My-appsody-stack:0.4
Running command: docker run --rm -v appsody-controller-0.3.5:/.appsody appsody/init-controller:0.3.5
Unable to find image 'appsody/init-controller:0.3.5' locally
0.3.5: Pulling from appsody/init-controller
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
[Error] exit status 125
```

How can I create/pull appsody image for the M1 chipset?

**Comment by dawoodahmed-jazz** [comment]
resolved using following command

**Comment by dawoodahmed-jazz** [comment]
Resolved using the following command

`docker pull --platform linux/x86_64`

**Comment by angelicaba23** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/72242331/161129266-1163d978-63c5-4e7f-ace7-244af8563e58.png">
Hi, I hope you're good.
I'm having the same problem, con you help me pls. Thanks in advance.

**Comment by dawoodahmad** [comment]
have you tried this one??

docker pull --platform linux/x86_64

**Comment by NoumanDilshad-Systems** [comment]
> <img alt="image" width="1024" src="https://user-images.githubusercontent.com/72242331/161129266-1163d978-63c5-4e7f-ace7-244af8563e58.png">
> 
> Hi, I hope you're good. I'm having the same problem, con you help me pls. Thanks in advance.

Please try this,

docker pull --platform linux/x86_64 appsody/init-controller:0.3.5
